// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MulticlassRace.Data;

#nullable disable

namespace multi_class_race_dashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924083816_AddResultSnapshotColumnsToDriverStanding")]
    partial class AddResultSnapshotColumnsToDriverStanding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MulticlassRace.Models.AssettoCorsaGameConfig", b =>
                {
                    b.Property<Guid>("AssettoCorsaGameConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GamePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceResultsPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssettoCorsaGameConfigId");

                    b.ToTable("AssettoCorsaGameConfigs");
                });

            modelBuilder.Entity("MulticlassRace.Models.Championship", b =>
                {
                    b.Property<Guid>("ChampionshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChampionshipName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChampionshipId");

                    b.ToTable("Championships");
                });

            modelBuilder.Entity("MulticlassRace.Models.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Car")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DriverAgression")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DriverStrength")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("DriverId");

                    b.HasIndex("TeamId");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("MulticlassRace.Models.DriverStanding", b =>
                {
                    b.Property<Guid>("DriverStandingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BestLapTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassPosition")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LapCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OriginalTeamId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DriverStandingId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SessionId");

                    b.ToTable("DriverStandings");
                });

            modelBuilder.Entity("MulticlassRace.Models.PointSetting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingId");

                    b.ToTable("PointSettings");

                    b.HasData(
                        new
                        {
                            SettingId = new Guid("d8f10b2a-5a6b-4c7d-8e9f-0a1b2c3d4e5f"),
                            Config = "{\"1\":25,\"2\":18,\"3\":15,\"4\":12,\"5\":10,\"6\":8,\"7\":6,\"8\":4,\"9\":2,\"10\":1}",
                            IsDefault = true,
                            SettingName = "Standard"
                        });
                });

            modelBuilder.Entity("MulticlassRace.Models.Race", b =>
                {
                    b.Property<Guid>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PointSettingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("RaceId");

                    b.HasIndex("PointSettingId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("MulticlassRace.Models.Season", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChampionshipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeasonId");

                    b.HasIndex("ChampionshipId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("MulticlassRace.Models.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("RaceId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("MulticlassRace.Models.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamLogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamClassId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MulticlassRace.Models.TeamClass", b =>
                {
                    b.Property<Guid>("TeamClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamClassId");

                    b.ToTable("TeamClasses");

                    b.HasData(
                        new
                        {
                            TeamClassId = new Guid("2254e881-f300-4154-a84f-600196de6081"),
                            IsActive = true,
                            TeamClassName = "Hypercar"
                        },
                        new
                        {
                            TeamClassId = new Guid("2254e881-f300-4154-a84f-600196de6082"),
                            IsActive = true,
                            TeamClassName = "LMP2"
                        },
                        new
                        {
                            TeamClassId = new Guid("2254e881-f300-4154-a84f-600196de6083"),
                            IsActive = true,
                            TeamClassName = "GT3"
                        });
                });

            modelBuilder.Entity("RaceTeam", b =>
                {
                    b.Property<Guid>("EnteredTeamsTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("EnteredTeamsTeamId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceTeam");
                });

            modelBuilder.Entity("MulticlassRace.Models.Driver", b =>
                {
                    b.HasOne("MulticlassRace.Models.Team", "Team")
                        .WithMany("Drivers")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MulticlassRace.Models.DriverStanding", b =>
                {
                    b.HasOne("MulticlassRace.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulticlassRace.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulticlassRace.Models.Session", null)
                        .WithMany("DriverStandings")
                        .HasForeignKey("SessionId");

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("MulticlassRace.Models.Race", b =>
                {
                    b.HasOne("MulticlassRace.Models.PointSetting", "PointSetting")
                        .WithMany()
                        .HasForeignKey("PointSettingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MulticlassRace.Models.Season", "Season")
                        .WithMany("Races")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointSetting");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MulticlassRace.Models.Season", b =>
                {
                    b.HasOne("MulticlassRace.Models.Championship", "Championship")
                        .WithMany("Seasons")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");
                });

            modelBuilder.Entity("MulticlassRace.Models.Session", b =>
                {
                    b.HasOne("MulticlassRace.Models.Race", "Race")
                        .WithMany("Sessions")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("MulticlassRace.Models.Team", b =>
                {
                    b.HasOne("MulticlassRace.Models.TeamClass", "TeamClass")
                        .WithMany("Teams")
                        .HasForeignKey("TeamClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamClass");
                });

            modelBuilder.Entity("RaceTeam", b =>
                {
                    b.HasOne("MulticlassRace.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("EnteredTeamsTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulticlassRace.Models.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MulticlassRace.Models.Championship", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("MulticlassRace.Models.Race", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MulticlassRace.Models.Season", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("MulticlassRace.Models.Session", b =>
                {
                    b.Navigation("DriverStandings");
                });

            modelBuilder.Entity("MulticlassRace.Models.Team", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("MulticlassRace.Models.TeamClass", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
